### ISSUE TITLE
Climate

### ISSUE THREAD

**Issue by Cino2424** [Xenomes/Domoticz-TUYA-Plugin#1]
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'max_temper': 99,
                                                  'min_temper': 0,
                                                  'mode': 'hot',
                                                  'online': True,
                                                  'state': 'false',
                                                  'support_mode': [   'cold',
                                                                      'hot',
                                                                      'wind',
                                                                      'auto'],
                                                  'temp_unit': 'CELSIUS',
                                                  'temperature': 31},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',

**Comment by Xenomes** [comment]
Which device do you have?

**Comment by Cino2424** [comment]
Its a split climate. brand TCL

**Comment by Xenomes** [comment]
I put this one on my to-do list, i need to improve my programing skills. before i can add multiple devices in Domoticz to control a single Tuya-device. Because i don't have the device myself can't test/debug the new code.

**Comment by ScIT-Raphael** [comment]
@Cino2424 may I ask, on which app you added your TCL AC? There is a "SmartLife-SmartHome" app from ACSmart (where you need the TCL activation code for) which i currently use. But the app seems to have encrypted communication. Were you able to join your AC to the "default" tuya app? Or have you made additional changes to get that output?

@Xenomes thanks for the fork, I'll have a look, maybe I can help expand the AC part :).

**Comment by Cino2424** [comment]
> @Cino2424 may I ask, on which app you added your TCL AC? There is a "SmartLife-SmartHome" app from ACSmart (where you need the TCL activation code for) which i currently use. But the app seems to have encrypted communication. Were you able to join your AC to the "default" tuya app? Or have you made additional changes to get that output?
> 
> @Xenomes thanks for the fork, I'll have a look, maybe I can help expand the AC part :).

Ich benutze die normale Smart Life App. Mit dem Plugin habe ich die Klimageräte auch in Domoticz drin. Kann sie aber nur ein und ausschalten.

I use the standard Smart Life App without Activation Code. The Plugin adds the Climate in Domoticz, but only with Power off and on. No way to change running mode or Temp change.

**Comment by ScIT-Raphael** [comment]
Deutsch geht auch :). Also die nicht gebrandete, "offene" Variante (https://play.google.com/store/apps/details?id=com.tuya.smartlife)? Wie hast du da die Klima hinzugefügt? Ich hab bei mir 5 Stück im Einsatz, würde das sonst gleich mal testen. Bis jetzt hatte ich leider keinen Zugriff auf die Schnittstelle, da die Geschichte bei der TCL Variante scheinbar verschlüsselt läuft.

For all non german/swiss friends:
So the unbranded, "open" variant (https://play.google.com/store/apps/details?id=com.tuya.smartlife)? How did you add the climate there? I have 5 of them in use, I would test them right away. Until now I had no access to the interface, because the story seems to be encrypted in the TCL version.

**Comment by Cino2424** [comment]
Du ich hab die Klima in den Verbindungsmodus gesetzt und bei der Smart Life App Klima ausgewählt. Frag mich jetzt aber nicht welche, gibt da wohl unterschiedliche. Kann mit der App auch jeden Modus benutzen. Das einzige ist halt nur dann mit der Fernbedienung. Hab da eine mit LCD die weiß dann halt nicht was die Klima gerade macht. Muss dann manuell mit der Fernbedienung etwas auswählen, damit auf dem LCD das Richtige dann angezeigt wird.

**Comment by ScIT-Raphael** [comment]
Super, ich teste das Morgen, danke für die Infos! Hab im Moment die Modellreihe AX21, teils AX91 im Einsatz, die Fernbedienung ist jeweils mit Infrarot und LCD, so wie du dies beschreibst - bei mir ist die gar nicht im Betrieb, liegt auf der Klima. Das Ding ist halt einfach aufgrund von Infrarot "blöde", kann sich halt nicht mit dem Tuya/ESP Modul synchronisieren (one way). Ich gebe Morgen mal kurz Bescheid, wie und ob das geklappt hat - dann kann ich mich um die Integration kümmern, falls ich das hinkrieg.

**Comment by Xenomes** [comment]
> @Xenomes thanks for the fork, I'll have a look, maybe I can help expand the AC part :).

That would be great 👍🏻

**Comment by ScIT-Raphael** [comment]
@Cino2424 Kurz zum bestätigen, du hattest recht. Die Klima in den Pair Modus schmeissen, Smart Life App öffnen und "Klimaanlage" auswählen - that's all :). Da ich jetzt auch Zugriff drauf habe, schaue ich, ob ich die Teile nun auch in Domoticz reinkrieg - also mehr als Ein/Aus.

**Comment by Xenomes** [comment]
@ScIT-Raphael and did you make some progress?

**Comment by ScIT-Raphael** [comment]
Small steps: I got a current overview and I'm able to reach the tuya device of the AC itself. Now adding to domoticz is a bit more complicated, because there doesnt exist a "AC-Device" which combines all features of the ac itself in one device. Option A would be to split this to multiple switched (don't like that), Option B would be to add a new device which contains all functions in one - which is what I would love to. Currently stuck in the "add a new device" process in domoticz, which could include all features.

**Comment by Cino2424** [comment]
I would use 2 devices. One to set mode and one for temperature. Other Settings like fanspeed and windangle are not needed.
It should not be a replacement for the whole remote, just an option for automation to make it cold or hot.

Else it would to be overpowered.

**Comment by Xenomes** [comment]
I did start a small experiment with the climate.
https://github.com/Xenomes/Domoticz-TUYA-Plugin/tree/Climate_Test

**Comment by ScIT-Raphael** [comment]
Awesome, I still try to find some free time for development - but will have a look at your adjustment asap.

**Comment by ScIT-Raphael** [comment]
Hi Guys, I havnt forgotten you - still trying to find some free time :).

**Comment by ScIT-Raphael** [comment]
Hi Guys, me again. Just wanted to update that I switched from domoticz to home assistant. Needed some special modules which i wasnt able to find in domoticz. Noticed that they have air conditioners over tuya integrated and they are working properly. Sorry for the delay.

**Comment by Xenomes** [comment]
Hi, 
Climate is now available in a other plugin [TinyTUYA](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin)
