### ISSUE TITLE
no devices detected

### ISSUE THREAD

**Issue by GAUTIER44530** [Xenomes/Domoticz-TUYA-Plugin#10]
Hello, none of my devices added, there is no error in the log. can you help me ?

![image](https://user-images.githubusercontent.com/61647329/122533595-0d90f000-d022-11eb-9a56-cce0bac59f47.png)

**Comment by Xenomes** [comment]
The device count is 0, so there are no devices in your account or there is somting wrong. Please configure and run the debug_discovery.py from the tools directory and post the json output here.

**Comment by GAUTIER44530** [comment]
hello, here is the screenshot.
Thank you for your help

![image](https://user-images.githubusercontent.com/61647329/122596809-b6fbd400-d06a-11eb-8749-e0cfbce2358b.png)

**Comment by Xenomes** [comment]
that is not good, it is a Python script, please rerun as python3 ./debug_discovery.py also I see the tuyaha folder in the plugin map please remove and use the install guide for correct install.

**Comment by GAUTIER44530** [comment]
hello, here is the result

![image](https://user-images.githubusercontent.com/61647329/122642639-bd8e5800-d10b-11eb-8314-3fe2ab84cbb3.png)

**Comment by Xenomes** [comment]
It looks like you didn't configure the debug_discovery.py or the credentials are incorrect.

**Comment by Xenomes** [comment]
Problem solved?

**Comment by GAUTIER44530** [comment]
hello, sorry for my late reply, but i have been very busy.
I configured the debug, here is the return.
thank you

![image](https://user-images.githubusercontent.com/61647329/123588212-b93afc80-d7e7-11eb-9f55-faef81c7a94b.png)

**Comment by GAUTIER44530** [comment]
I found part of my error, I edit the file directly on my Rpi1, despite this I still have a password error. off I check it several times.

![image](https://user-images.githubusercontent.com/61647329/123589780-015b1e80-d7ea-11eb-8915-ea72c7d659b6.png)

**Comment by GAUTIER44530** [comment]
I have configured the debug like this, is there something else?

![image](https://user-images.githubusercontent.com/61647329/123607329-1346bc80-d7fe-11eb-8d4f-8bd0a09f61f6.png)

**Comment by Xenomes** [comment]
Config is looking good, is the BIZ_TYPE correct? I know there are some issue with a special symbols in a password, if you have one in the password that can be the problem.

**Comment by GAUTIER44530** [comment]
Hello
TO TEST MY ACCESS I use the user and password from  https://www.tuya.com/

?

**Comment by Xenomes** [comment]
It must be the credentials of the app you are using.
