### ISSUE TITLE
Make refresh period configurable

### ISSUE THREAD

**Issue by trekkir** [Xenomes/Domoticz-TUYA-Plugin#11]
Hi @Xenomes,
First of all, thank you for your work!
I do have a request; Currently, the refresh period is set to 10 seconds. Is it possible to make it configurable on the Hardware settings page? 

I can't seem to find the exact configuration in the python file to modify it myself (_basic programming knowledge on my side must be the problem here_), so if my request isn't something you want to implement, could you point me in the right direction where I can change that 10 seconds myself?

**Comment by Xenomes** [comment]
Hi Trekkir,
What is the reason you want a refresh period? If you want to change it I think the wait on line 210 is the best to start.

**Comment by trekkir** [comment]
Hi, I have a plug turning itself on when the doorbell camera is pushed (using the Tuya scene in the Tuya app itself).
A blocky event in Domotica triggers on the On state of that plug by triggering a script that will send me a snapshot of the doorbell camera by email and finally turning the plug back off.

But the 10s delay in your plugin means a maximum delay of 19s between pressing the doorbell and my script being executed and I would like to process that a bit faster.

I found the time.sleep at line 210, but doesn't that mean 0.5 seconds delay?




________________________________

**Comment by Xenomes** [comment]
Ok, I understand your problem. The 10 seconds I the shortest time I could get to pull data from the API of Tuya there is not a lot of time to win there.

**Comment by trekkir** [comment]
Ah ok, so it's not specified in the plugin itself?



________________________________

**Comment by Xenomes** [comment]
Nope. Maybe you can use a IFTTT or DZGA
