### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by laoil72** [Xenomes/Domoticz-TUYA-Plugin#15]
Hello, im using this device with the wireless zigbee gateway
![Screenshot_2021-07-22-05-56-52-595_com alibaba aliexpresshd](https://user-images.githubusercontent.com/68594459/126588215-d1db056d-e6b4-410f-ac11-e06c93917979.jpg)
Device appear in SmartLife with all my devices but not showed in Domoticz. Normal ?
Can i help you to integrate the device ?
Thanks

![Screenshot_2021-07-22-05-59-57-868_com android chrome](https://user-images.githubusercontent.com/68594459/126588357-78d53214-faad-47be-ba3a-9a812c9af7b1.jpg)

**Comment by Xenomes** [comment]
Device is not supported by the Tuya API V1.
