### ISSUE TITLE
Switch on, but no switch off?

### ISSUE THREAD

**Issue by sciurius** [Xenomes/Domoticz-TUYA-Plugin#18]
I have a Calex A60 RGB-CCT connected to Domiticz via the TUYA plugin. I can switch it off (and on) via the widget on the Switches page.

I have two timers, one to switch on at sunset, and one to switch off at 23.30.

![scrot20211108103244](https://user-images.githubusercontent.com/1118804/140899455-0b9839ad-7f7f-4c34-82b6-fa228b032dfa.png)

The lamp is switched on by the timer, but the switch off never happens.

**Comment by Xenomes** [comment]
I will look in to this, I will compare the normal off and the timer off maybe there is a difference.

**Comment by Xenomes** [comment]
@sciurius Are you on the stable or beta version?

**Comment by sciurius** [comment]
I checked out the master branch from git. Version seems to be 1.0.13.

I seems that yesterday (nov 9) it **did** get an off trigger.

![scrot20211110080502](https://user-images.githubusercontent.com/1118804/141065959-f912d59b-63e6-4973-923e-21178bedb3ee.png)

**Comment by Xenomes** [comment]
Sorry my bad, I mean the version of Domoticz 😅

**Comment by sciurius** [comment]
I assume stable:

About Domoticz
Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by Xenomes** [comment]
OK thanks!

**Comment by sciurius** [comment]
I must add that for the past couple of days, the lamp correctly switched off at the programmed time.

![scrot20211112093422](https://user-images.githubusercontent.com/1118804/141436152-c4bfcfc5-071e-49ca-b862-a03077d7f46d.png)

Could it have been a temporary connection failure?

**Comment by Xenomes** [comment]
Please keep monitoring... i did some test every time the light go's on or off.

**Comment by sciurius** [comment]
No abnormal behaviour for the last months. Thanks.
