### ISSUE TITLE
Recurring on/of events

### ISSUE THREAD

**Issue by sciurius** [Xenomes/Domoticz-TUYA-Plugin#19]
I have a Calex A60 RGB-CCT connected to Domiticz via the TUYA plugin. (This is not the one from issue #18.)

This lamp is powered on/off by a physical switch, which implies that is it offline when powered off.

When powered off, I notice continuous on/of events in the log, exactly every 70 seconds.

![scrot20211109110024](https://user-images.githubusercontent.com/1118804/140903385-cf536f22-19bb-418b-b0cc-fbab86a20cab.png)

**Comment by Xenomes** [comment]
I notice the same problem, will change the check to when changed.

**Comment by sciurius** [comment]
Confirmed.
