### ISSUE TITLE
plugin doesn't show under hardware

### ISSUE THREAD

**Issue by vespino** [Xenomes/Domoticz-TUYA-Plugin#21]
I'm running Domoticz in Docker on my Synology and I was hoping on adding a few Tuya/SmartLife products to the mix. I followed the instructions, got no errors, restarted Domoticz but can't seem to find "Tuya" under hardware.

Is there some way to verify the plugin is loaded and running like it should?

**Comment by vespino** [comment]
Guess it's Domoticz on Docker, I installed Domoticz in a VM and the plugin does show up. However: I'm not able to login to Tuya, I'm getting this error: Error: TuyaCloud: (TuyaCloud) handleThread: Get accesstoken failed. Invalid parms. line 207

The app works with the credentials I'm using in Domoticz. Any thoughts on this?

**Comment by vespino** [comment]
I have been able to solve this issue by using a less difficult password. Apparently the API or this plugin has difficulties processing special chars that I used.

**Comment by vespino** [comment]
Another comment on this: Domoticz in Docker (on Synology) stores plugins in a different directory than the regular install. After running the git clone command from the local directory, the plugin did load and I was able to add Tuya hardware using this plugin.

**Comment by Xenomes** [comment]
> I have been able to solve this issue by using a less difficult password. Apparently the API or this plugin has difficulties processing special chars that I used.

Yes his is a issue with the api, special characters are a problem. 

> Another comment on this: Domoticz in Docker (on Synology) stores plugins in a different directory than the regular install. After running the git clone command from the local directory, the plugin did load and I was able to add Tuya hardware using this plugin.
The docker plug-in installation is a other situation, if the api keep on working maybe I will update the readme.md.
