### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by sciurius** [Xenomes/Domoticz-TUYA-Plugin#22]
A question (since I don't know how to otherwise reach you).

Have you considered turning the plugin into a standalone TUYA-MQTT gateway so it is possible to control devices independent of Domiticz?

(Or maybe such a tool already exists?)

**Comment by Xenomes** [comment]
Hi,
No I didn't, my programming skills are not good enough to build a plug-in from scratch. I try to maintain the plug-in until the API stops working. The original code is not by my hands, only some improvements.
