### ISSUE TITLE
LDV Wifi - Get accesstoken failed

### ISSUE THREAD

**Issue by elxsi** [Xenomes/Domoticz-TUYA-Plugin#23]
Hi,

I'm having some difficulties using the TUYA plugin. I've tried running the debug_discovery.py (after setting the corresponding
configuration options), but I always get:

Getting credentials
Got credentials
{   'errorMsg': 'Get accesstoken failed. Username or password error!',
    'responseStatus': 'error'}

USERNAME = "<removed>"
PASSWORD = "<removed>"
REGION = "eu" # cn, eu, us
COUNTRY_CODE = "49" # Your account country code, e.g., 1 for USA or 86 for China
#BIZ_TYPE = "smart_life" # tuya, smart_life, jinvoo_smart
BIZ_TYPE = "tuya" # tuya, smart_life, jinvoo_smart
FROM = "tuya" # you likely don't need to touch this

My current testing password does not contain any special characters (only a-zA-Z and 0-9). I have a Ledvance Panel which
I can control using the LDV Wifi app using the same username/password. I've also tried the other two BIZ_TYPES without success.
Any ideas of how to proceed?

Thank you!

**Comment by Xenomes** [comment]
Hi,

Your device need to be in one of these apps ( tuya, smart_life, jinvoo_smart) to work. I don't know if you device supported by the old version of the tuya api.
