### ISSUE TITLE
Sensor or Siren Temp+Hum

### ISSUE THREAD

**Issue by Mimouss56** [Xenomes/Domoticz-TUYA-Plugin#24]
Hi
I bought Siren Temp+Hum
I saw them in TuyaIOT and not in DOmoticz

Device Information
Product Name
Siren Temperature and Humidity
Device ID
03067725......a0c2
Product Category
wsdcg
Device Status
Online
Activated At
2022-01-12 18:04:20
Device Association

Extension Information
Sub-Device or Not
No
IP Address
91.***.***.22

Did i make something wrong?

**Comment by Xenomes** [comment]
Temperature and Humidity devices are not supported by the plug-in, maybe the siren whit a on/off command.
Configure and run the debug_discovery.py you can see in the device json if there is an device.

**Comment by Mimouss56** [comment]
Do you know where i need to search in code for making great with temp and humidity ?

**Comment by Xenomes** [comment]
You first need to know if the api shows the temp and humidity by running the debug_discovery.py.

**Comment by Mimouss56** [comment]
API show them, i trying on line. I will try with debug discovery

**Comment by Xenomes** [comment]
The online Tuya IOT is the new API, the plug-in is using the old one. not all devices where listed on the IOT will list debug_discovery.py

**Comment by Mimouss56** [comment]
I keep you in touch

**Comment by Xenomes** [comment]
👍🏻

**Comment by Mimouss56** [comment]
ImportError: No module named requests

requests is installed via pip3

**Comment by Xenomes** [comment]
Try running the python script with sudo.

**Comment by Mimouss56** [comment]
same

**Comment by Xenomes** [comment]
did you run it with pyhton3 ./debug_discovery.py ?

**Comment by Mimouss56** [comment]
my bad i ran with python xD

snif i don't see my devices
do you know some plugins else for me?

**Comment by Xenomes** [comment]
I was afraid for that. I don't know a plug-in that is working with the new api. I hope someone from the community will built a new plug-in for the tuya cloud. I have only one rgbw light that I don't use any more, most devices I use are zigbee or shelly/tasmota.

**Comment by Mimouss56** [comment]
thx well
