### ISSUE TITLE
No device found for SAS980SWT (zigbee)

### ISSUE THREAD

**Issue by duc31** [Xenomes/Domoticz-TUYA-Plugin#26]
Hi all,

Even if I unfortunalty got not doubt that  the device is not detected...
There is a strange behaviour within the debug script, or maybe I misunderstood something.

I followed all instructions, and the  device is not recognized by domoticz when I look at the Log : Device Count : 0   ( yes this is my first device)

But when I shedule a scene in Tuya App, the debug script provide below result:
### python3 ./debug_discovery.py
![image](https://user-images.githubusercontent.com/3127638/157532081-7bf0de8b-cfda-4d86-8cde-61b91ab536eb.png)
As you can see, a device is found, but this is the scene.

Any chance I can connect the device, from your point of view ? The device is a switch on/off (https://www.saswell.com/smart-irrigation-wifi-water-timer-sas980swt-7-z01_p147.html)

I found a workaround... creating a scene with this device : action of switching. 
It's also possible to create two scenes... one for "off", one for "on"... Because it looks like domoticz doesn't take the value of the first solution.

Best regards,
duc

**Comment by Xenomes** [comment]
Zigbee is not supported by the Tuya API V1.
