### ISSUE TITLE
Tuya plugin do Not see Wifi and zegbee devices

### ISSUE THREAD

**Issue by gbananachewicz** [Xenomes/Domoticz-TUYA-Plugin#27]
Tuya plugin 1.0.13 
I see only 4-ch wifi switch, scene's and Tap to run.

Do Not see Wifi door sensor, Zegbee wifi gateway and devices under zegbee.

**Comment by Xenomes** [comment]
Zigbee is not supported by the Tuya API V1.

**Comment by gbananachewicz** [comment]
Bit when i use tuya-cli wizard, I see all devices under tuya !!! Their id and keys.
