### ISSUE TITLE
Smart wifi plug

### ISSUE THREAD

**Issue by edwin123456** [Xenomes/Domoticz-TUYA-Plugin#29]
Hi xenomes,
Is there also support for the tuya smart wifi plug
Switch on,off 
And power readings?

Thanks
Greetings 
Edwin

**Comment by varazir** [comment]
I'm looking for this as well 

I'm planing to buy this Smart plug with Power Meter  (GP300)
Planingen to use it my bathroom to my washing machine.  Both 

TIA 
Daniel

**Comment by Xenomes** [comment]
In this plugin it is not possible, we are building a other plugin https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin.
Power readings are not programed yet, but it is planned.

**Comment by varazir** [comment]
> In this plugin it is not possible, we are building a other plugin https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin. Power readings are not programed yet, but it is planned.

Okay thanks, I think I have a older plugin, going to check when I get home again. 
I use it for a floor stand fan less air cleaner.

**Comment by Xenomes** [comment]
Power readings are now in the Develop of TinyTuya plugin.
