### ISSUE TITLE
Cover (and curtain track) Update Domoticz Status when opening/closing

### ISSUE THREAD

**Issue by davewins** [Xenomes/Domoticz-TUYA-Plugin#33]
Code for Open/Close cover requires updating so that it updates the Domoticz status correctly:

change the code from:

elif dev_type == 'cover':
            if Command == 'Open':
                dev.open_cover()
            elif Command == 'Stop':
                dev.stop_cover()
            elif Command == 'Close':
                dev.close_cover()
            UpdateDevice(Unit, 1, 'On', not dev.available())
to:

elif dev_type == 'cover':
            if Command == 'Open':
                dev.open_cover()
                UpdateDevice(Unit, 1, 'On', not dev.available())
            elif Command == 'Stop':
                dev.stop_cover()
            elif Command == 'Close':
                dev.close_cover()
                UpdateDevice(Unit, 0, 'Off', not dev.available());

**Comment by Xenomes** [comment]
Hi davewins,
I think by the new cover control that the code can be:
```
elif dev_type == 'cover':
if Command == 'Open':
dev.open_cover()
UpdateDevice(Unit, 1, 'Open', not dev.available())
elif Command == 'Stop':
dev.stop_cover()
UpdateDevice(Unit, 0, 'Stop', not dev.available())
elif Command == 'Close':
dev.close_cover()
UpdateDevice(Unit, 0, 'Close', not dev.available())
```

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Open-Close_Blinds

**Comment by Xenomes** [comment]
The plugin is fixed.
