### ISSUE TITLE
Cover Status update issue

### ISSUE THREAD

**Issue by davewins** [Xenomes/Domoticz-TUYA-Plugin#34]
When Domoticz queries the status of a device, the Cover/Blinds/Curtain always returns a status of 3, which is neither open or closed. In this code:

                # Update device
                if dev.state() == False:
                    UpdateDevice(unit, 0, 'Off', not dev.available())
                elif dev.state() == True:
                    UpdateDevice(unit, 1, 'On', not dev.available())
                else:
                    Domoticz.Log('DeviceID='+Devices[unit].DeviceID+' State update skiped. status = '+str(dev.state())+' device type = '+str(dev.device_type()))

I added the device type to show that it is the Cover always reaching the Else block as the state is always 3.

Any ideas how we can get the status of the cover? In my case it's the Q1500 curtain track from Quoya

**Comment by Xenomes** [comment]
With some testers we are building a new Tuya plugin.
https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin
Can you create a debug.json by edit/running debug-discovery.py with python3 from the tools directory (Domoticz-TinyTUYA-Plugin).

**Comment by davewins** [comment]
Ok - here's the json file as requested.

Let me know if I can help any further

dave

**Comment by Xenomes** [comment]
Thanks but the file from the mail is not include on github, can you resend the mail to xenomes@outlook.com?

**Comment by Xenomes** [comment]
The plugin is fixed.
