### ISSUE TITLE
Plugin is not working anymore...

### ISSUE THREAD

**Issue by Barry40** [Xenomes/Domoticz-TUYA-Plugin#38]
After a year or so i updated all my plugins to latest versions, but only this plugin remains to work anymore.
Went back to TUYA Plugin v.1.0.13 wich is working again..
I don't know what the faulty is, but its just to let you know that your latest v1.0.15 is not working with my domoticz anymore :)

**Comment by Xenomes** [comment]
What is the error message you are getting?

**Comment by Barry40** [comment]
No error, no debug, nothing.
Removed plugin, reinstalled, etc, but nothing helped.
Downgrade to my old plugin fixed it.

**Comment by Xenomes** [comment]
Strange, just install it on my fresh test system. Device is detected and i can control it. What kind of device you can't control any more?

**Comment by Barry40** [comment]
A roller shade.

BENEXMART Tuya Roller Shade Driver:
(Tuya zigbee + Rf) https://amzn.eu/d/8jEUrmw

Op wo 15 mrt. 2023 20:48 schreef Xenomes ***@***.***>:

**Comment by Xenomes** [comment]
ha ok... what is the version of you Domoticz?

**Comment by Barry40** [comment]
Version: 2023.1 (build 15153)
Build Hash: 4b2bf07d6
Compile Date: 2023-03-14 16:12:50
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

Op wo 15 mrt. 2023 21:14 schreef Xenomes ***@***.***>:

**Comment by Xenomes** [comment]
The plugin is fixed.
