### ISSUE TITLE
Method [Discovery] fails

### ISSUE THREAD

**Issue by pe1ago** [Xenomes/Domoticz-TUYA-Plugin#39]
self.tuya._discovery_interval = 600
TUYA: handleThread: Method [Discovery] fails 1 time(s) using poll interval 600 - error: you can discovery once in 1020 seconds line 219
Line 219: self.devs = self.tuya.get_all_devices()

btw: Thanks for a very fine plugin.

**Comment by Xenomes** [comment]
Hi pe1ago,
I can't replicate the issue, on my test system.
If the problem still exists try change line 197 the wait time 61 to 103
`        if time.time() - self.last_update < 103:`
