### ISSUE TITLE
Tuya Smart Plug with meters

### ISSUE THREAD

**Issue by Martijn085** [Xenomes/Domoticz-TUYA-Plugin#4]
Thanks for all your great work, my Tuya Smart Plug works great with this plugin.

Would it be possible to also make the Watt, Voltage, Ampere and kWh meter avalible for the Tuya Smart Plug?
I have used this plugin before: https://github.com/sincze/Domoticz-Tuya-SmartPlug-Plugin only this requires a membership for the Tuya IoT Platform for which they charge no less than $300!

**Comment by Xenomes** [comment]
That is not yet possible, this plug-in is am depending how the tuyaha works.
