### ISSUE TITLE
Get access token failed

### ISSUE THREAD

**Issue by thibautautrive** [Xenomes/Domoticz-TUYA-Plugin#40]
Hi, 

I try to use the plugin but i always have the error "Tuya: handleThread: Get accesstoken failed. Username or password error! line 211"

I tried to use my account on [https://iot.tuya.com/](url) (email and password).
I also tried to use api credentials but still same issue. 

Did i miss something ? 

Thank you

**Comment by Xenomes** [comment]
Hi thibautautrive,
This plugin uses the login of the Smart Life, Jinvoo Smart or Tuya app.
The https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin use the iot account of tuya.

**Comment by thibautautrive** [comment]
Hello, 

I use the same account on the app and iot platform (email and password).
I finally connect with using my phone number and change my password.

Thank you for the answer and plugin :)
