### ISSUE TITLE
Retrieving measurements of consumption

### ISSUE THREAD

**Issue by ricorico94** [Xenomes/Domoticz-TUYA-Plugin#42]
Hi,
This is not really an issue of the plugin because it on contrary works well for me. But I use it to control some power plugs, which are able to provide the measurement of power (cumulative and instantaneous).
Would there be any way to implement this as a measurement device in domoticz ?
Thanks a lot for your current plugin anyway !

**Comment by Xenomes** [comment]
Hi,
This plug-in is not able to read power measurements, the Tuyaha library is not maintained anymore. I have build a other plugin that can do power measurements, see https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin every 6 months the iot license need to be extend.
