### ISSUE TITLE
1.0.15 blinds not working

### ISSUE THREAD

**Issue by Barry40** [Xenomes/Domoticz-TUYA-Plugin#43]
Hi,
V1.0.15 blinds are not working.
Downgrade to v1.0.12 fixed it again.

**Comment by Barry40** [comment]
2023-04-16 12:14:01.723 Status: Tuya: Started.
2023-04-16 12:14:01.723 Status: Tuya: Entering work loop.
2023-04-16 12:14:02.163 Status: Tuya: Initialized version 1.0.15, author 'Wagner Oliveira contributed Xenomes'

Enabled debug, but no debug is seen, nothing else in log is seen after starting the plugin.

**Comment by Xenomes** [comment]
What is the version of you Domoticz?

**Comment by Barry40** [comment]
2023.1 build 15182

Op zo 16 apr. 2023 14:56 schreef Xenomes ***@***.***>:

**Comment by Xenomes** [comment]
> Enabled debug, but no debug is seen, nothing else in log is seen after starting the plugin.

That is strange there must be more logging. At the start the plugin wait for 60sec to connect to tuya.
the 60sec is a countdown of 10 sec a status message in the log.

**Comment by Barry40** [comment]
I did, also disabling / re-enabling the plugin did nothing.
1.0.12 works correctly.

 

Van: Xenomes ***@***.***> 
Verzonden: zondag 16 april 2023 15:17
Aan: Xenomes/Domoticz-TUYA-Plugin ***@***.***>
CC: ***@***.*** ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Xenomes/Domoticz-TUYA-Plugin] 1.0.15 blinds not working (Issue #43)

 

Enabled debug, but no debug is seen, nothing else in log is seen after starting the plugin.
That is strange there must be more logging. At the start the plugin wait for 60sec to connect to tuya.
the 60sec is a countdown of 10 sec a status message in the log.

**Comment by Xenomes** [comment]
The version 1.0.12 is before the change from on/off to open/close. But you are on 2023.1 so open/close command would be send.
Created a test branch can you pull it and test? the command could be logged.

**Comment by Barry40** [comment]
Okay!

Op zo 16 apr. 2023 19:20 schreef Xenomes ***@***.***>:

**Comment by Barry40** [comment]
Yes, test git works after a minute or so!
Still no debugging in log, but great job :)
I will leave the branche to test till you update the  master again 👌🏿

**Comment by Xenomes** [comment]
Thanks for reporting back! Strange it are normal log commands.

**Comment by Barry40** [comment]
Your welcome! You thanks for changing the code to a working version again 🙏🏾
I think i know why the debug is not seen, i have disabled status messages in my Domoticz. Only error is seen. 
I have so many devices that will let the log grow so big that its not funny to see or find a status or message..

Domoticz is started with loglevel 2.

**Comment by Xenomes** [comment]
Ha that is the issue with the logging 😆

**Comment by Xenomes** [comment]
Push the test to master

**Comment by Barry40** [comment]
> Push the test to master

Great, thanks.
Updated to master and will let you know :)
