### ISSUE TITLE
Only one device added with a duo dimmer

### ISSUE THREAD

**Issue by quukske77** [Xenomes/Domoticz-TUYA-Plugin#44]
Hi,

I added the TUYA plugin to my Domoticz  installation.
It can find my TUYA dimmer and i can control it.
But this is a duo dimmer which controls 2 lights.
In the TUYA app i can control both.
The TUYA plugin only added one device in Domoticz.
So i can only control  one light.
It it possible to see it is a duo dimmer?
And if so can the plugin added an extra device to Domoticz?

**Comment by Xenomes** [comment]
HI Quuksje77,
I don't know if the second control is detected.
Can you fill in and run the debug_discovery.py and post the outcome?

**Comment by quukske77** [comment]
This is the output.
I cleared the id.

Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'brightness': '310',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1552276718127bcUlE/1663401319d3c2b67a2f1.png',
                                      'id': '.....................',
                                      'name': 'ECO-DIM.05 WiFi Led dimmer'}],
                   'scenes': []}}

**Comment by Xenomes** [comment]
The export shows no second switch/dimmer. Think best option is to try the tinytuya there are more devices supported.
https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin

**Comment by quukske77** [comment]
I tried that plugin and it worked for me. Thanks!!!

**Comment by Xenomes** [comment]
Good to hear, if you account is new remember that in some time you will to renew the tuya subscription.
