### ISSUE TITLE
can not see PIR 

### ISSUE THREAD

**Issue by wirszews** [Xenomes/Domoticz-TUYA-Plugin#45]
Hi,
I've WIFI PIR NEO MOTION SENSOR (NAS-PD02W)

https://pl.aliexpress.com/item/32883051053.html

Is it possible for Plugin to see it?

Unfortunately, he can't see it, only if I add a scene for him

` python3 ./debug_discovery.py
Getting credentials
Got credentials
{   'access_token': 'EUheu1684691333591pl9SPHy7XXXXXX',
    'expires_in': 864000,
    'refresh_token': 'EUheu1684691333591pl9SPYhXXXXXX',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'hYQl7dhIIMMr3Bnn',
                                      'name': 'If Motion Sensor Motion '
                                              'Sensor:Alarm'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
`

**Comment by Xenomes** [comment]
No this old tuya library can't detect the pir devices. You cab try this one uses the tinytuya as library .
https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin
