### ISSUE TITLE
Water valve controller not supported

### ISSUE THREAD

**Issue by the-master006** [Xenomes/Domoticz-TUYA-Plugin#47]
Hello,
I noticed that the water valve controller (I have a Wi-Fi variant) is not supported. Is it possible to add? It is very similar to an on/off switch. Thanks!

**Comment by Xenomes** [comment]
Hi, Can you edit/run the discovery_debug.py and share the json. if this shows the data then it can be included otherwise you can turn to the Tinytuya plugin.

**Comment by the-master006** [comment]
In the json I see only my "switches" just powerplugs, but no code from this water valve controller. So I will try the tinytuya plugin. Thanks!

**Comment by Xenomes** [comment]
Thanks for reporting back.
