### ISSUE TITLE
Add support for Woox  smart irrigator

### ISSUE THREAD

**Issue by galadril** [Xenomes/Domoticz-TUYA-Plugin#49]
I have this smart irrigator from Woox, and its connected via the Smart life app, but i dont see the device in domoticz.
https://www.reichelt.nl/nl/nl/slimme-besturing-voor-tuinirrigatie-wifi-woox-r4238-p348344.html

Any ideas on how this could be added?

**Comment by Xenomes** [comment]
This newer type of devices is not compatible with the old API. The newer https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin will work or can be updated to support the device.

**Comment by galadril** [comment]
Thanks, closed
