### ISSUE TITLE
No feedback sent to the domoticz

### ISSUE THREAD

**Issue by plontajos** [Xenomes/Domoticz-TUYA-Plugin#51]
Hello,

Thanks for developing this great app ;)

There is no feedback sent to Domoticz after phisical change of the switch. Everything ok I Tuya app.

This is general issue or not for this switch?

Switch equipment: Spectrum smart WOJ+05416
https://sklep.spectrumled.pl/en_GB/p/Spectrum-SMART-light-switch%2C-dual-zone%2C-white/8
Domoticz version: 2023.2
Build Hash: 19efd039c
Compile Date: 2023-07-21 17:23:44
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by Xenomes** [comment]
The plugin reads once a minute if the status is changed.
