### ISSUE TITLE
New device WIFI Dual Meter1 not detected

### ISSUE THREAD

**Issue by moipopples** [Xenomes/Domoticz-TUYA-Plugin#52]
Hello i have adevice not detected it is a power meter.

    "name": "WIFI Dual Meter1",
    "id": "xxx",
    "key": "Deleted",
    "mac": "1xxx",
    "uuid": "xxx",
    "sn": "10011988600795",
    "category": "zndb",
    "product_name": "WIFI Dual Meter",
    "product_id": "z95s7p3z54xbsjnl",
    "biz_type": 0,
    "model": "PJ1103A",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16111967609110m8U/c30343574ee42145af0ffa5a0924e40b.png"

Properties of device: 
 {
  "result": {
    "category": "zndb",
    "functions": [
      {
        "code": "forward_energy_total",
        "desc": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}",
        "name": "\u6b63\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "reverse_energy_total",
        "desc": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}",
        "name": "\u53cd\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "forward_energy_total",
        "name": "\u6b63\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "reverse_energy_total",
        "name": "\u53cd\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "total_power",
        "name": "\u603b\u529f\u7387",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":-99999999,\"max\":99999999,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1700242349338,
  "tid": "4821b0d1856f11eea84192c59b34336d"
}

Status of device: 
 {
  "result": [
    {
      "code": "forward_energy_total",
      "value": 0
    },
    {
      "code": "reverse_energy_total",
      "value": 0
    },
    {
      "code": "total_power",
      "value": 0
    }
  ],
  "success": true,
  "t": 1700242349517,
  "tid": "483be546856f11eea84192c59b34336d"
}

**Comment by Xenomes** [comment]
For the TinyTUYA Plugin.
