### ISSUE TITLE
Adding measures from devices (smartplugs for instance)

### ISSUE THREAD

**Issue by ricorico94** [Xenomes/Domoticz-TUYA-Plugin#6]
Hi,
So far, I'm using the Guino branch of the plugin to switch on/off my smartplugs, but I see that your plugin might be more advanced as it now includes also some lights.
Do you think you could include in your plugin the retrieve of measures done by devices like SmartPlugs (voltage, current, consumption) ?
There used to be a plugin doing it: [https://github.com/sincze/Domoticz-Tuya-SmartPlug-Plugin](url)
 I didn't try it and I'm not sure if it still works as it is now old, but tracking voltage and current would be great.
br,

**Comment by Xenomes** [comment]
Hi, sorry that is not possible jet, the plug-in you mention use local communication, Guino and my modified version of the Guino are using the tuyaha library, which use the official Tuya API but the API is under develop from the Tuya company. The only thing we can try is to report the unsupported devices. as mention there https://github.com/PaulAnnekov/tuyaha#my-device-is-not-listed-in-tuya-api-response-or-contains-incomplete-state-what-should-i-do
